---
config:
  layout: dagre
---
erDiagram
	direction LR
	USERS {
		INTEGER ID PK "NOT NULL"
		INTEGER DISCORD_ID "DiscordのユーザーID, NOT NULL"
		INTEGER JOB_ID "職業, NOT NULL"
		INTEGER CASH "所持金, NOT NULL"
		INTEGER ENERGY "活動エネルギー, NOT NULL"
		INTEGER HOUSE_CHANNEL_ID "ハウスチャンネルのID"
		INTEGER TELL_THREAD_ID "TELLスレッドのID"
		TEXT ACTED_AT "最後に行動した時間"
	}
	
	ITEMS {
		INTEGER ID PK "NOT NULL"
		TEXT NAME "アイテム名, NOT NULL"
		TEXT DESCRIPTION "アイテムの説明"
		TEXT TYPE "アイテムのタイプ, NOT NULL"
	}
	
	ITEM_RECIPES {
		INTEGER ID PK "NOT NULL"
		INTEGER ITEM_ID "NOT NULL"
		TEXT RECIPE "NOT NULL"
	}
	
	ITEM_ENERGY {
		INTEGER ID PK "NOT NULL"
		INTEGER ITEM_ID "NOT NULL"
		INTEGER ENERGY "NOT NULL"
	}
	
	INVENTORY {
		INTEGER ID PK "NOT NULL"
		INTEGER USER_ID "持ち主のID, NOT NULL"
		INTEGER ITEM_ID "アイテムのID, NOT NULL"
		INTEGER AMOUNT "量, NOT NULL"
	}
	
	MARKET {
		INTEGER ID PK "NOT NULL"
		INTEGER SELLER_ID "販売者のID, NOT NULL"
		INTEGER ITEM_ID "アイテムのID, NOT NULL"
		INTEGER AMOUNT "量, NOT NULL"
		INTEGER PRICE "価格, NOT NULL"
		TEXT LISTED_AT "出品された日時, NOT NULL"
	}
	
	JOBS {
		INTEGER ID PK "NOT NULL"
		TEXT NAME "職業名, NOT NULL"
		INTEGER TOOL_ID "使う道具のID"
		INTEGER PRODUCT_ID "生産するアイテムのID"
	}
	
	TRADE_LOGS {
		INTEGER ID PK "NOT NULL"
		INTEGER PROVIDER_ID "提供者のID NOT NULL"
		INTEGER RECIPIENT_ID "受給者のID NOT NULL"
		INTEGER ITEM_ID "取引したアイテムのID"
		INTEGER AMOUNT "取引したアイテムの量"
		INTEGER CASH_AMOUNT "取引した通貨の量"
		TEXT PLACE "取引の場所(market or private) NOT NULL"
		TEXT TRADED_AT "取引の日時, NOT NULL"
	}
	
	USERS ||--o{ INVENTORY : "ID : USER_ID"
	USERS ||--|| JOBS: "JOB_ID : ID"
	
	INVENTORY }o--|| ITEMS : "ITEM_ID : ID"
	MARKET }o--|| ITEMS : "ITEM_ID : ID"
	MARKET }o--|| USERS : "SELLER_ID : ID"
	
	JOBS }o--|| ITEMS : "TOOL_ID : ID"
	JOBS }o--|| ITEMS : "PRODUCT_ID : ID"
	
	ITEMS ||--o| ITEM_RECIPES : "ID : ITEM_ID"
	ITEMS ||--o| ITEM_ENERGY : "ID : ITEM_ID"
	
	TRADE_LOG }o--|| USERS : "PROVIDER_ID : ID"
	TRADE_LOG }o--|| USERS : "RECIPIENT_ID : ID"
	TRADE_LOG }o--|| ITEMS : "ITEM_ID : ID"
	